Repository CruSea/soul-sync-frontend, pull requests merged in 2024-12, with the labels that each got.

#34 33 Make a signup page
  app/globals.css
  components/shared/UserActions.tsx
  components/ui/dropdown-menu.tsx
  components/views/auth/sign-in.tsx
  package-lock.json
  package.json
  public/assets/signIn.png
  tailwind.config.ts
Labels: Features

#43 42 redo page routing for frontend
  app/admin/agents/page.tsx
  app/admin/channels/page.tsx
  app/admin/mentors/page.tsx
  app/admin/messages/page.tsx
  app/admin/page.tsx
  app/admin/users/page.tsx
  app/mentor/page.tsx
  app/user/page.tsx
  components/views/auth/sign-in.tsx
  package-lock.json
Labels: Chore

#52 style: change the style of header component
  components/shared/Header.tsx
Labels: Style

#58 57 create layout for create organization page
  app/(auth)/create-org/page.tsx
  components/shared/CreateOrgSidebar.tsx
  components/shared/LandingPageHeader.tsx
  components/shared/LoginPageCard.tsx
  components/shared/UserActions.tsx
  components/views/auth/create-org.tsx
  components/views/auth/log-in.tsx
Labels: Features

#64 63 make the admin messages board
  components/shared/Chat.tsx
  components/shared/ChatHeader.tsx
  components/shared/layout/admin-layout.tsx
  components/shared/layout/sidebar.tsx
  components/ui/command.tsx
  components/views/admin/messages.tsx
Labels: Features

#86 84 add mentor info filling out page
  app/(dashboard)/(routes)/mentor/get-started/page.tsx
  app/(dashboard)/(routes)/mentor/page.tsx
  app/layout.tsx
  components/shared/CreateOrg/CompanyDomainField.tsx
  components/shared/CreateOrg/CompanyNameField.tsx
  components/shared/CreateOrg/CreateOrgForm.tsx
  components/shared/CreateOrg/CreateOrgSidebar.tsx
  components/shared/CreateOrg/FocusField.tsx
  components/shared/CreateOrg/FormOne.tsx
  components/shared/CreateOrg/FormTwo.tsx
  components/shared/CreateOrg/RoleField.tsx
  components/shared/CreateOrg/SizeField.tsx
  components/shared/CreateOrgSidebar.tsx
  components/shared/GetStarted/AgeField.tsx
  components/shared/GetStarted/DayPeriod.tsx
  components/shared/GetStarted/GenderField.tsx
  components/shared/GetStarted/GetStartedCard.tsx
  components/shared/GetStarted/GetStartedForm.tsx
  components/shared/GetStarted/GetStartedSidebar.tsx
  components/shared/GetStarted/LocationField.tsx
  components/shared/GetStarted/MinuteField.tsx
  components/shared/GetStarted/SpecializationField.tsx
  components/shared/GetStarted/TimeCommand.tsx
  components/shared/GetStarted/TimePopover.tsx
  components/shared/GetStarted/hourField.tsx
  components/shared/LandingPage/LandingPageBody.tsx
  components/shared/LandingPage/LandingPageFooter.tsx
  components/shared/LandingPage/LandingPageHeader.tsx
  components/shared/LandingPageBody.tsx
  components/shared/LoginPage/LoginPageCard.tsx
  components/shared/LoginPage/LoginPageSidebar.tsx
  components/shared/LoginPageCard.tsx
  components/shared/Main.tsx
  components/shared/UserActions.tsx
  components/ui/checkbox.tsx
  components/ui/popover.tsx
  components/ui/radio-group.tsx
  components/ui/toast.tsx
  components/views/admin/messages.tsx
  components/views/auth/create-org.tsx
  components/views/auth/log-in.tsx
  components/views/landing-page.tsx
  components/views/mentor/get-started.tsx
  components/views/mentor/mentor-chat.tsx
  content/page.ts
  data/create-org.ts
  data/get-started-data.ts
  data/users.ts
  package-lock.json
  package.json
  public/assets/mentorGetStarted.png
  tailwind.config.ts
  types/create-org.ts
  types/get-started.ts
  types/users.ts
Labels: Features

#88 82 update the channels page for the admin
  components/shared/Channel/add-channel-dialog.tsx
  components/shared/Channel/channel-card.tsx
  components/shared/Channel/channel-config-form.tsx
  components/shared/Channel/channel-name-form.tsx
  components/shared/Channel/channel-type-form.tsx
  components/shared/MessageTable.tsx
  components/shared/UserTable.tsx
  components/shared/add-channel-dialog.tsx
  components/shared/admins.tsx
  components/shared/channel-card.tsx
  components/shared/invite-admin-dialog.tsx
  components/shared/invite-mentor-dialog.tsx
  components/shared/layout/sidebar.tsx
  components/ui/command.tsx
  components/views/admin/channel.tsx
  data/message_data.ts
  data/sidebar.ts
  data/users.ts
  public/Facebook.svg
  public/Twilio.png
  tailwind.config.ts
  types/channel.ts
  types/users.ts
Labels: Features

#90 89 add functionality to delete button in channel card
  components/shared/Channel/channel-card.tsx
  components/shared/DataTable.tsx
  components/shared/dashboard/UserTable.tsx
  components/views/admin/channel.tsx
Labels: Features

#94 93 create a mock db for the adminchannels page and integrate it
  channels-db.json
  components/shared/Channel/add-channel-dialog.tsx
  components/shared/Channel/channel-card.tsx
  components/shared/add-channel-dialog.tsx
  components/views/admin/channel.tsx
  package-lock.json
  package.json
  types/channel.ts
Labels: Features

#101 100 creating a toast on the channels
  channels-db.json
  components/shared/Channel/channel-card.tsx
  components/shared/add-channel-dialog.tsx
  components/shared/layout/admin-layout.tsx
  components/views/admin/channel.tsx
  package-lock.json
  package.json
Labels: Features
