Repository CruSea/soul-sync-frontend, pull requests merged in 2025-01, with the labels that each got.

#107 104 change the format of form for channnel
  channels-db.json
  components/shared/Channel/add-channel-dialog.tsx
  components/shared/Channel/channel-api-form.tsx
  components/shared/Channel/channel-campId-form.tsx
  components/shared/Channel/channel-card.tsx
  components/shared/Channel/channel-token-form.tsx
  components/shared/Channel/channel-type-form.tsx
  components/shared/Chat.tsx
  components/shared/layout/header.tsx
  components/views/admin/channel.tsx
  data/sidebar.ts
  package.json
  types/channel.ts
Labels: Features

#109 108 fix styling on the channels card
  channels-db.json
  components/shared/Channel/channel-card.tsx
  components/shared/Chat.tsx
  components/shared/layout/header.tsx
Labels: Style

#111 110 refactor channel configuration display div into separate components
  channels-db.json
  components/shared/Channel/ChannelConfig/Facebook.tsx
  components/shared/Channel/ChannelConfig/Negarit.tsx
  components/shared/Channel/ChannelConfig/NegaritSMS.tsx
  components/shared/Channel/ChannelConfig/Whatsapp.tsx
  components/shared/Channel/ChannelConfig/telegramBot.tsx
  components/shared/Channel/ChannelConfig/twilio.tsx
  components/shared/Channel/add-channel-dialog.tsx
  components/shared/Channel/channel-card.tsx
  components/shared/Channel/channel-token-form.tsx
  components/shared/Channel/channel-type-form.tsx
  components/views/admin/channel.tsx
  data/sidebar.ts
  types/channel.ts
Labels: Chore

#124 123 fix our expected responses to requests based on new backend schema
  .eslintrc.json
  components/shared/admin/admin-mentors/mentors.tsx
  components/views/auth/log-in.tsx
  data/end-points.ts
Labels: bug

#125 121 connect the channels with the backend
  .eslintrc.json
  components/shared/Channel/channel-card.tsx
  components/shared/LoginPage/LoginPageCard.tsx
  components/views/admin/channel.tsx
  components/views/admin/dashboard.tsx
  data/end-points.ts
Labels: Features

#128 127 fixing api integration
  actions/admin/action.ts
  actions/admin/admin.ts
  actions/admin/channel.ts
  actions/admin/metore.ts
  actions/base-api-request/apiRequest.ts
  actions/middleware/api.ts
  app/(dashboard)/(routes)/admin/messages/page.tsx
  components/shared/Channel/channel-card.tsx
  components/shared/LoginPage/LoginPageCard.tsx
  components/shared/admin/admin-mentors/mentors.tsx
  components/shared/layout/sidebar.tsx
  components/ui/switch.tsx
  components/views/admin/channel.tsx
  components/views/admin/create-org.tsx
  components/views/admin/dashboard.tsx
  context/AuthContext.tsx
  package-lock.json
  package.json
  pnpm-lock.yaml
  types/channel.ts
  types/requests/index.ts
Labels: enhancement
