Repository CruSea/soul-sync-frontend, pull requests merged in 2025-02, with the labels that each got.

#134 131 api integration
  actions/admin/action.ts
  actions/admin/admin.ts
  actions/admin/channel.ts
  actions/admin/metore.ts
  actions/auth/auth.ts
  actions/auth/login.ts
  actions/middleware/api.ts
  actions/revalidate.ts
  actions/shared/dataTable.ts
  actions/shared/userTable.ts
  app/(auth)/log-in/page.tsx
  app/(dashboard)/(root)/page.tsx
  app/(dashboard)/(routes)/admin/agents/page.tsx
  app/(dashboard)/(routes)/admin/channels/page.tsx
  app/(dashboard)/(routes)/admin/create-org/page.tsx
  app/(dashboard)/(routes)/admin/dashboard/page.tsx
  app/(dashboard)/(routes)/admin/layout.tsx
  app/(dashboard)/(routes)/admin/mentees/page.tsx
  app/(dashboard)/(routes)/admin/mentors/page.tsx
  app/(dashboard)/(routes)/admin/messages/page.tsx
  app/(dashboard)/(routes)/admin/page.tsx
  app/(dashboard)/(routes)/admin/users/page.tsx
  app/(dashboard)/(routes)/mentor/layout.tsx
  app/layout.tsx
  components/shared/DataTable.tsx
  components/shared/LandingPage/LandingPageBody.tsx
  components/shared/LoginPage/LoginPageCard.tsx
  components/shared/MessageTable.tsx
  components/shared/admin/admin-mentors/invite-mentor-dialog.tsx
  components/shared/admin/admin-mentors/mentees.tsx
  components/shared/admin/admin-mentors/mentors.tsx
  components/shared/admin/dashboard/UserTable.tsx
  components/shared/admins.tsx
  components/shared/layout/mentor-layout.tsx
  components/views/admin/channel.tsx
  components/views/admin/create-org.tsx
  components/views/admin/dashboard.tsx
  components/views/admin/messages.tsx
  components/views/auth/log-in.tsx
  components/views/landing-page.tsx
  components/views/mentor/mentor-chat.tsx
  context/AuthContext.tsx
  context/withAuth.tsx
  data/end-points.ts
  db.json
  lib/utils.ts
  mentee-db.json
  middleware.ts
  next.config.ts
  package.json
  pnpm-lock.yaml
  types/mentor.ts
  types/requests/index.ts
  types/users.ts
Labels: Chore

#136 135 notification
  app/(dashboard)/(routes)/mentor/layout.tsx
  app/api/auth/[...nextauth]/callback/google.ts
  app/api/auth/[...nextauth]/options.ts
  app/api/auth/[...nextauth]/route.ts
  app/layout.tsx
  components/shared/Channel/configuration/Whatsapp.tsx
  components/shared/LoginPage/LoginPageCard.tsx
  middleware.ts
  types/channel.ts
Labels: bug

#138 137 fix pip line
  .eslintrc.json
  actions/user/get-user.ts
  components/shared/Channel/channel-card.tsx
  components/shared/Channel/configuration/twilio.tsx
  components/shared/Chat.tsx
  components/shared/GetStarted/GetStartedAdminForm.tsx
  components/shared/GetStarted/GetStartedMentorForm.tsx
  components/shared/add-channel-dialog.tsx
  components/shared/admin/admin-mentors/mentors.tsx
  components/views/User.tsx
  components/views/admin/channel.tsx
  components/views/admin/create-org.tsx
  components/views/mentor/mentor-chat.tsx
  types/channel.ts
Labels: Chore

#141 reday to production
  components/shared/LoginPage/LoginPageCard.tsx
Labels: Chore

#169 168 refactor connect channel
  actions/admin/admin.ts
  actions/admin/channel.ts
  components/shared/Channel/channel-card.tsx
  components/shared/admin/admin-mentors/invite-mentor-dialog.tsx
  components/shared/admin/admin-mentors/mentees.tsx
  components/shared/admin/admin-mentors/mentors.tsx
  components/shared/admin/dashboard/user-table.tsx
  components/shared/admins.tsx
  components/shared/data-table.tsx
  components/shared/message-table.tsx
  components/views/admin/channel.tsx
  types/channel.ts
Labels: Chore

#167 refactor: replace 'any' type with 'unknown' for improved type safety …
  base-api/api.ts
  base-api/method.ts
  components/views/admin/channel.tsx
Labels: Chore

#174 162 fix minor bugs
  actions/auth/auth.ts
  components/login-page/login-page-card.tsx
  components/views/auth/log-in.tsx
  types/users.ts
Labels: bug

#177 171 message log table
  actions/admin/channel.ts
  actions/shared/data-table.ts
  actions/shared/user-table.ts
  app/(dashboard)/admin/messages/page.tsx
  base-api/method.ts
  components/shared/admin/admin-mentors/mentees.tsx
  components/shared/admin/admin-mentors/mentors.tsx
  components/shared/admin/admin-messages/message-table.tsx
  components/shared/admin/dashboard/user-table.tsx
  components/shared/message-table.tsx
  components/views/admin/channel.tsx
  data/end-points.ts
  data/message_data.ts
  public/assets/confused.jpg
  types/message.ts
Labels: Chore

#180 106 make mentor edit profile page
  .env.dev
  app/(dashboard)/(routes)/mentor/profile/page.tsx
  components/shared/Mentor/Profile/account-img.tsx
  components/shared/Mentor/Profile/basic-info.tsx
  components/shared/Mentor/Profile/specialization.tsx
  components/shared/layout/accountDialog.tsx
  components/shared/layout/header.tsx
  components/views/mentor/profile.tsx
Labels: Features

#182 fix: update handleToggle to accept channelId and manage state correctly
  components/shared/Channel/channel-card.tsx
Labels: Chore

#183 feat: enhance channel fetching with pagination support
  .vscode/settings.json
  actions/admin/channel.ts
  components/views/admin/channel.tsx
Labels: Chore

#186 feat: Refactor the data table fetching
  actions/shared/data-table.ts
  components/shared/admin/admin-mentors/mentors.tsx
  components/shared/admin/admin-messages/message-table.tsx
  components/shared/data-table.tsx
Labels: Chore

#188 187 disable connect button after connecting
  actions/admin/channel.ts
  components/shared/Channel/channel-card.tsx
Labels: Chore

#192 116 change mentor page to work based on new backend schema
  .env.dev
  .env.prod
  actions/mentor/mentor.ts
  actions/revalidate.ts
  app/(dashboard)/mentor/error.tsx
  app/(dashboard)/mentor/layout.tsx
  app/api/mentor/users.ts
  components/shared/LoginPage/LoginPageCard.tsx
  components/shared/Mentor/Chat.tsx
  components/shared/Mentor/Message.tsx
  components/shared/Mentor/chat-header.tsx
  components/shared/Mentor/conversations-list.tsx
  components/shared/Mentor/input-area.tsx
  components/shared/Mentor/mentor-container.tsx
  components/shared/layout/mentor-layout.tsx
  components/views/mentor/mentor-chat.tsx
  context/providers/SocketProvider.tsx
  data/end-points.ts
  data/mentor.ts
  db.json
  lib/utils.ts
  package-lock.json
  package.json
  pnpm-lock.yaml
  public/facebook.png
  types/mentor.ts
Labels: duplicate

#189 185 block the admin from going to mentor page and viseversa
  actions/admin/admin.ts
  actions/auth/login.ts
  app/(dashboard)/admin/layout.tsx
  app/(dashboard)/mentor/layout.tsx
  components/login-page/login-page-card.tsx
  components/shared/admin/admin-mentors/mentors.tsx
  components/shared/admin/admin-messages/message-table.tsx
  components/views/admin/channel.tsx
  components/views/admin/create-org.tsx
  components/views/admin/dashboard.tsx
  components/views/mentor/mentor-chat.tsx
  middleware.ts
  types/users.ts
Labels: bug, Chore
